### ISSUE TITLE
[Bug report] Validation still fail after enter correct card number

### ISSUE THREAD

**Issue by zentetsukenz** [omise/validator.js#3]
This bug report is based on feature/implement-validation-rules commit 85bc627

#### Possible cause

According to this line

https://github.com/omise/validator.js/blob/feature/implement-validation-rules/src/coffee/validations/ccnumber.coffee#L80

`value` will be a number with spaces. But according to the regex in `isCard` function

https://github.com/omise/validator.js/blob/feature/implement-validation-rules/src/coffee/validations/validates.coffee#L20

This expect the number that don't have any spaces. Hence, it will always return false and validation will never pass.

**Comment by guzzilar** [comment]
Fixed in https://github.com/omise/validator.js/commit/ff11ca703401a2f333847d839aa7e118495d4fb6
